aplicações/agenda/config/routes.rb
Rails.application.routes.draw do
  
  get 'home/index'
  get '/inicio' => 'home#index' 
  
  root 'home#index'

  resources :contatos_telefones
  resources :contatos_enderecos
  resources :contatos
  resources :telefones
  resources :enderecos
  resources :tipos

end

aplicações/agenda/app/models/tipo.rb
class Tipo < ActiveRecord::Base
  has_many :contatos
end

aplicações/agenda/app/controllers/tipos_controller.rb
class TiposController < ApplicationController
  before_action :set_tipo, only: [:show, :edit, :update, :destroy]

  # GET /tipos
  # GET /tipos.json
  def index
    @tipos = Tipo.all
  end

  # GET /tipos/1
  # GET /tipos/1.json
  def show
  end

  # GET /tipos/new
  def new
    @tipo = Tipo.new
  end

  # GET /tipos/1/edit
  def edit
  end

  # POST /tipos
  # POST /tipos.json
  def create
    @tipo = Tipo.new(tipo_params)

    respond_to do |format|
      if @tipo.save
        format.html { redirect_to tipos_path, notice: I18n.t('message.created') }
        format.json { render :show, status: :created, location: @tipo }
      else
        format.html { render :new }
        format.json { render json: @tipo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tipos/1
  # PATCH/PUT /tipos/1.json
  def update
    respond_to do |format|
      if @tipo.update(tipo_params)
        format.html { redirect_to tipos_path, notice: I18n.t('message.updated') }
        format.json { render :show, status: :ok, location: @tipo }
      else
        format.html { render :edit }
        format.json { render json: @tipo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tipos/1
  # DELETE /tipos/1.json
  def destroy
    @tipo.destroy
    respond_to do |format|
      format.html { redirect_to tipos_url, notice: I18n.t('message.destroyed') }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tipo
      @tipo = Tipo.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tipo_params
      params.require(:tipo).permit(:descricao)
    end
end

aplicações/agenda/app/helpers/tipos_helper.rb
module TiposHelper
end

aplicações/agenda/app/views/tipos/_form.html.erb
<%= form_for(@tipo, html: { class: "form-style-5" }) do |f| %>

  <h1>Novo Tipo</h1><br>

  <fieldset>
    <legend><span class="number">1</span> Descricao</legend>
    <div class="field">
      <%= f.text_field :descricao, placeholder: "#{:descricao}" %>
    </div>

    <% if @tipo.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@tipo.errors.count, "error") %> prohibited this tipo from being saved:</h2>

        <ul>
        <% @tipo.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

    <div class="actions" style="display: flex; justify-content: space-around;">
      <span style="width: 40%">
        <%= f.submit t('buttons.save'), class: "btn btn-success btn-block"%>
      </span>
      <span style="width: 40%">
        <%= link_to t('buttons.back'), tipos_path, class: "btn btn-primary btn-block"%>
      </span>
    </div>
  </fieldset>
<% end %>

aplicações/agenda/app/views/tipos/edit.html.erb
<h1>Editing Tipo</h1>

<%= render 'form' %>

<%= link_to 'Show', @tipo %> |
<%= link_to 'Back', tipos_path %>

aplicações/agenda/app/views/tipos/index.html.erb
<div class="form-style-5">
  <script>
    $.notify("<%= notice %>", "success");
  </script>

  <h1>Listando Tipos</h1>

  <table class="table table-striped">
    <thead>
      <tr>
        <th>Descricao</th>
        <th colspan="2" style="text-align:center">Ações</th>
      </tr>
    </thead>

    <tbody>
      <% @tipos.each do |tipo| %>
        <tr>
          <td><%= tipo.descricao %></td>
          <td> <%= link_to t('buttons.edit'), edit_tipo_path(tipo) %> </td>
          <td> <%= link_to t('buttons.destroy'), tipo, method: :delete, data: { confirm: t('message.confirm') } %> </td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <br>

  <%= link_to t('buttons.new'), new_tipo_path, class: "btn btn-success"%>
  <%= link_to t('buttons.home'), root_path, class: "btn btn-primary"%>
</div>

aplicações/agenda/app/views/tipos/new.html.erb
<%= render 'form' %>

aplicações/agenda/app/views/tipos/show.html.erb
<div class="form-style-5">

  <p id="notice"><%= notice %></p>
  
  <p>
    <strong>Descricao:</strong>
    <%= @tipo.descricao %>
  </p>
  
  <%= link_to 'Edit', edit_tipo_path(@tipo) %> |
  <%= link_to 'Back', tipos_path %>
  
</div>