aplicações/teste-cilia/config/routes.rb
Rails.application.routes.draw do
  root 'home#index'

  devise_for :customers, controllers: {
    registrations: 'customers/registrations'
  }
  devise_scope :customer do
    delete 'customers/cancel', to: 'devise/registrations#cancel', as: nil
  end

  devise_for :admins, skip: [:registrations]
  as :admin do
    get 'admins/edit' => 'devise/registrations#edit', as: 'edit_admin_registration'
    put 'admins' => 'devise/registrations#update', as: 'admin_registration'
  end
  devise_scope :admin do
    delete 'admins/cancel', to: 'devise/registrations#cancel', as: nil
  end
  
  resources :sales, except: [:destroy] do
    collection do
      get :index_admin, path: 'admin/index'
    end
    member do
      get :cancel
      get :complete
      get :show_admin, path: 'admin/show'
      get :cancel_admin, path: 'admin/cancel'
    end
  end

  resources :products, except: [:destroy] do
    member do
      get :activate
      get :deactivate
    end
  end

  resources :phones
  resources :addresses
  resources :customers, except: [:new, :destroy] do
    member do
      get :activate
      get :deactivate
    end
  end
end

aplicações/teste-cilia/app/controllers/addresses_controller.rb
class AddressesController < ApplicationController
  before_action :authenticate_customer!
  before_action :set_address, only: %i[ show edit update destroy ]

  # GET /addresses or /addresses.json
  def index
    @addresses = Address.where(customer_id: current_customer.id)
  end

  # GET /addresses/1 or /addresses/1.json
  def show
  end

  # GET /addresses/new
  def new
    @address = Address.new
  end

  # GET /addresses/1/edit
  def edit
  end

  # POST /addresses or /addresses.json
  def create
    @address = Address.new(address_params)
    @address.customer = current_customer

    respond_to do |format|
      if @address.save
        format.html { redirect_to address_url(@address), notice: "O endereço foi criado com sucesso." }
        format.json { render :show, status: :created, location: @address }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @address.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /addresses/1 or /addresses/1.json
  def update
    respond_to do |format|
      if @address.update(address_params)
        format.html { redirect_to address_url(@address), notice: "O endereço foi atualizado com sucesso." }
        format.json { render :show, status: :ok, location: @address }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @address.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /addresses/1 or /addresses/1.json
  def destroy
    respond_to do |format|
      if @address.destroy
        format.html { redirect_to addresses_url, notice: "O endereço foi excluído com sucesso." }
        format.json { head :no_content }
      else
        format.html { redirect_to addresses_url, alert: @address.errors.full_messages.join('. ')}
        format.json { head :unprocessable_entity }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_address
      @address = Address.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def address_params
      params.require(:address).permit(:street, :number, :district, :city, :state, :zipcode, :customer_id)
    end
end

aplicações/teste-cilia/app/views/addresses/_form.html.erb
<%= form_with(model: address, local: true) do |form| %>
  <% if address.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(address.errors.count, "erros") %> proibiram que este endereço fosse salvo::</h2>

      <ul>
      <% address.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :street %>
    <%= form.text_field :street %>
  </div>

  <div class="field">
    <%= form.label :number %>
    <%= form.text_field :number %>
  </div>

  <div class="field">
    <%= form.label :district %>
    <%= form.text_field :district %>
  </div>

  <div class="field">
    <%= form.label :city %>
    <%= form.text_field :city %>
  </div>

  <div class="field">
    <%= form.label :state %>
    <%= form.text_field :state %>
  </div>

  <div class="field">
    <%= form.label :zipcode %>
    <%= form.text_field :zipcode %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

aplicações/teste-cilia/app/views/addresses/edit.html.erb
<h1>Editing Address</h1>

<%= render 'form', address: @address %>

<%= link_to 'Show', @address %> |
<%= link_to 'Back', addresses_path %>

aplicações/teste-cilia/app/views/addresses/index.html.erb
<p id="notice"><%= notice %></p>
<p id="alert"><%= alert %></p>

<h1>Addresses</h1>

<table>
  <thead>
    <tr>
      <th>#</th>
      <th>Logradouro</th>
      <th>Número</th>
      <th>Bairro</th>
      <th>Cidade</th>
      <th>Estado</th>
      <th>CEP</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @addresses.each do |address| %>
      <tr>
        <td><%= address.id %></td>
        <td><%= address.street %></td>
        <td><%= address.number %></td>
        <td><%= address.district %></td>
        <td><%= address.city %></td>
        <td><%= address.state %></td>
        <td><%= address.zipcode %></td>
        <td><%= link_to 'Show', address %></td>
        <td><%= link_to 'Edit', edit_address_path(address) %></td>
        <td><%= link_to 'Destroy', address, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Novo Endereço', new_address_path %><br>

aplicações/teste-cilia/app/views/addresses/new.html.erb
<h1>New Address</h1>

<%= render 'form', address: @address %>

<%= link_to 'Voltar', addresses_path %>

aplicações/teste-cilia/app/views/addresses/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Logradouro:</strong>
  <%= @address.street %>
</p>

<p>
  <strong>Número:</strong>
  <%= @address.number %>
</p>

<p>
  <strong>Bairro:</strong>
  <%= @address.district %>
</p>

<p>
  <strong>Cidade:</strong>
  <%= @address.city %>
</p>

<p>
  <strong>Estado:</strong>
  <%= @address.state %>
</p>

<p>
  <strong>CEP:</strong>
  <%= @address.zipcode %>
</p>

<%= link_to 'Editar', edit_address_path(@address) %> |
<%= link_to 'Voltar', addresses_path %>